sudo: false
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - 'iojs'
install:
  - npm install
  - npm run setup
before_script:
  - psql -c "CREATE USER koalesce WITH PASSWORD 'koalesce';" -U postgres
  - psql -c 'CREATE DATABASE koalesce_test;' -U postgres
